name: Deploy static site to Azure Web App - Wa-testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # No build step needed for static HTML site
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: static-site

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_029221B580EE4B54A002F5C26214E995 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6132AFBE9B934018948F725036B30B1B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_02D0DF14A6D844DE8619CB37E07C7B1C }}
          client-secret: ${{ secrets.AZUREAPPSERVICE_CLIENTSECRET }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Wa-testing'
          slot-name: 'Production'
          package: .
