name: Deploy static site to Azure Web App - Wa-testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Login to Azure using Service Principal
      - name: Login to Azure
        uses: azure/login@v2
        with:
          auth-type: SERVICE_PRINCIPAL
          client-id: 762681b2-f77b-452c-a50c-3bcff6c5f1f4
          tenant-id: 3e1e0d01-08b0-4362-aa17-224e849224f1
          subscription-id: 60822fda-c35a-4f73-a010-956060e8b0b7
          client-secret: 2SU8Q~HiH51lsRGbaIKHO8XVIh4MtfuTisG~TcQu

      # Step 3: Deploy static site to Azure Web App
      - name: Deploy static site to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Wa-testing'
          slot-name: 'Production'
          package: .
