name: Deploy static site to Azure Web App - Wa-testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write       # Required for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          auth-type: OIDC
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}

      - name: Deploy static site to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Wa-testing'
          slot-name: 'Production'
          package: .
